### ISSUE TITLE
Bug Report: can't compile 

### ISSUE THREAD

**Issue by gummybear17** [CryBitDev/Sonic.exe-source#4]
/Users/jonathangomez/Desktop/Sonic.exe-source-master/source/vlc/cpp/src/LibVLC.cpp:4:10: warning: non-portable path to file '<stdint.h>'; specified path differs in case from file name on disk [-Wnonportable-include-path]
#include <StdInt.h>
         ^~~~~~~~~~
         <stdint.h>
/Users/jonathangomez/Desktop/Sonic.exe-source-master/source/vlc/cpp/src/LibVLC.cpp:5:10: fatal error: 'windows.h' file not found
#include <windows.h> 
         ^~~~~~~~~~~
1 warning and 1 error generated. 
how do i fix this plus im on mac

**Comment by CryBitDev** [comment]
Sadly, mp4 video support isn't for macOS devices. You can try making a virtuual machine using VirtualBox (https://virtualbox.org). However, if your mac is low on resources (RAM, GPU) this one isn't suggested.

**Comment by 448L** [comment]
you can use webm instead

**Comment by gummybear17** [comment]
how did you fix it? @448L

**Comment by 448L** [comment]
what I did was not to use the library to play mp4 or not use videos with that codec and container, I replaced them with webm videos with its vp8 and vorbis codec since they worked fine, and that was it.

But I had to program a little bit to do that.
I still left the videos, but they will only be used in windows since apparently they only work well there. a small example.

```haxe
new FlxTimer().start(1, function(tmr:FlxTimer)
                {
                    #if windows
                    var video:MP4Handler = new MP4Handler();
                    video.playMP4(Paths.video('tooslowcutscene1'), new PlayState());
                    #end

                    FlxG.switchState(new VideoState('assets/videos/tooslowcutscene1.webm', new PlayState()));
                    LoadingState.loadAndSwitchState(new PlayState(), true); //save this code for the cutsceneless build of the game
                });
```

you will have to transcode the mp4 videos **(H264 acc)** to webm **(vp8 vorbis)**, and a text file with the same name of your video ending in .txt and enter there the total amount of frames of the video.

and when you have done that, (in theory you are no longer using that library **"libvlc"**), it is possible that it will work, I am not so sure because your operating system is different from mine, but give it a try.

sorry for the possible bad English, it is not the language I speak.

**Comment by CryBitDev** [comment]
@448L Thanks for giving a solid answer to this question, i will be now closing this issue.
